# name: Terraform apply

# on:
#   push: #or use workflow_dispatch for manual runs
#     branches:
#       - main
#     paths:
#       - terraform/**

# env:
#   AWS_REGION: eu-west-2

# jobs:
#   apply:
#     runs-on: ubuntu-latest #change to a static version
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.AWS_REGION }}

#       - name: Setup Terraform 
#         uses: hashicorp/setup-terraform@v3

#       - name: Init
#         run: terraform init -input=false

#       - name: Apply
#         run: terraform apply -auto-approve

name: terraform-apply

on:
  push:
    branches: [ main ]
    paths: [ "terraform/**" ]
  workflow_dispatch: {}   # manual runs from the Actions tab

env:
  AWS_REGION: eu-west-2
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "0"

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform   # point to TF dir

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8  # version

      - name: Terraform init
        run: terraform init 

      - name: Terraform apply
        run: terraform apply -auto-approve
