name: Terraform Destroy

on:
    workflow_dispatch:


env:
    AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: "eu-west-2"

jobs:
    destroy:
        name: Terraform Destroy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                node-version: 14.x
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ env.AWS_ACCESS_ID }}
                aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY}}
                aws-region: ${{ env.AWS_REGION }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2

            - name: Initialise project and destroy terraform resources
              run: |
                cd terraform
                terraform fmt
                terraform init
                terraform destroy -auto-approve