
name: Terraform Apply

on:
    workflow_dispatch: # manual apply on github UI

env:
    AWS-ACCESS-ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
    AWS-SECRET-ACCESS-KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS-REGION: "eu-west-2"

jobs:
    apply:
        name: Terraform Apply
        runs-on: unbuntu-latest

        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ env.AWS-ACCESS-ID }}
                aws-secret-access-key: ${{ env.AWS-SECRET-ACCESS-KEY }}
                aws-region: ${{ env.AWS-REGION }}

            - name: Setup Terraform #install terraform as we are going to run terraform commands
              uses: hashicorp/setup-terraform@v2

            - name: Initialise project and view terraform plan
              run: |
                cd terraform
                terraform fmt
                terraform init
                terraform apply 